# Generated by Django 4.2.1 on 2023-07-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
