dinner_name = ['Liam Olivia', 'Noah emma', 'Theodore Harper', 'Henry Evelyn']
print(f"Dear {dinner_name[0].title()},please have a dinner with me.")
print(f"Dear {dinner_name[1].title()},please have a dinner with me.")
print(f"Dear {dinner_name[2].title()},please have a dinner with me.")
print(f"Dear {dinner_name[3].title()},please have a dinner with me.")
print("I find a bigger dinner table.")
dinner_name.insert(0, '123 456')
dinner_name.insert(3, 'Alex Jordan')
dinner_name.append('new world')
print(f"Dear {dinner_name[0].title()},please have a dinner with me.")
print(f"Dear {dinner_name[1].title()},please have a dinner with me.")
print(f"Dear {dinner_name[2].title()},please have a dinner with me.")
print(f"Dear {dinner_name[3].title()},please have a dinner with me.")
print(f"Dear {dinner_name[4].title()},please have a dinner with me.")
print(f"Dear {dinner_name[5].title()},please have a dinner with me.")
print(f"Dear {dinner_name[6].title()},please have a dinner with me.")
