dinner_name = ['Liam Olivia', 'Noah emma', 'Theodore Harper', 'Henry Evelyn']
print(f"Dear {dinner_name[0].title()},please have a dinner with me.")
print(f"Dear {dinner_name[1].title()},please have a dinner with me.")
print(f"Dear {dinner_name[2].title()},please have a dinner with me.")
print(f"Dear {dinner_name[3].title()},please have a dinner with me.")
print("I find a bigger dinner table.")
dinner_name.insert(0, '123 456')
dinner_name.insert(3, 'Alex Jordan')
dinner_name.append('new world')
print(f"Dear {dinner_name[0].title()},please have a dinner with me.")
print(f"Dear {dinner_name[1].title()},please have a dinner with me.")
print(f"Dear {dinner_name[2].title()},please have a dinner with me.")
print(f"Dear {dinner_name[3].title()},please have a dinner with me.")
print(f"Dear {dinner_name[4].title()},please have a dinner with me.")
print(f"Dear {dinner_name[5].title()},please have a dinner with me.")
print(f"Dear {dinner_name[6].title()},please have a dinner with me.")
print("Sorry, I could just invite two honored guest to join my dinner.")
del_customer = dinner_name.pop()
print(f"Sorry, I can't invite you, dear {del_customer.title()}.")
del_customer = dinner_name.pop()
print(f"Sorry, I can't invite you, dear {del_customer.title()}.")
del_customer = dinner_name.pop()
print(f"Sorry, I can't invite you, dear {del_customer.title()}.")
del_customer = dinner_name.pop()
print(f"Sorry, I can't invite you, dear {del_customer.title()}.")
del_customer = dinner_name.pop()
print(f"Sorry, I can't invite you, dear {del_customer.title()}.")
print(f"Dear {dinner_name[0].title()}, you still invited")
print(f"Dear {dinner_name[1].title()}, you still invited")
del dinner_name[0]
del dinner_name[0]
print(dinner_name)
