# Generated by Django 4.2.1 on 2023-07-23 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='topping',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
