# Generated by Django 4.2.1 on 2023-07-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizza_date_added_topping_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'topping'},
        ),
    ]
